/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/menModel/menFutbolka/menFutbolka.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MenFutbolka(props) {
  const { nodes, materials } = useGLTF(
    "/menModel/menFutbolka/menFutbolka.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["men-futbolka"].geometry}
        material={materials.FABRIC_1_FRONT_4910}
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/menModel/menFutbolka/menFutbolka.gltf");
