/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/menModel/menModel.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MenModel(props) {
  const { nodes, materials } = useGLTF("/menModel/menModel.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes["men-model_1"].geometry}
          material={
            materials.M_Thomas_Sneaker_A_03_Male_Sneaker_02_opencollada_Female_Sneake
          }
        />
        <mesh
          geometry={nodes["men-model_2"].geometry}
          material={
            materials.M_Thomas_Sneaker_A_03_Male_Sneaker_02_opencollada_Female_Sn
          }
        />
        <mesh
          geometry={nodes["men-model_3"].geometry}
          material={materials.defaultMat1}
        />
        <mesh
          geometry={nodes["men-model_4"].geometry}
          material={materials.face}
        />
        <mesh
          geometry={nodes["men-model_5"].geometry}
          material={materials.body2}
        />
        <mesh
          geometry={nodes["men-model_6"].geometry}
          material={materials.arm}
        />
        <mesh
          geometry={nodes["men-model_7"].geometry}
          material={materials.leg}
        />
        <mesh
          geometry={nodes["men-model_8"].geometry}
          material={materials.eye}
        />
        <mesh
          geometry={nodes["men-model_9"].geometry}
          material={materials.eyelash}
        />
        <mesh
          geometry={nodes["men-model_10"].geometry}
          material={materials.toothSG1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/menModel/menModel.gltf");
