/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/futbolka/futbolkagltf.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Futbolka(props) {
  const { nodes, materials } = useGLTF("/futbolka/futbolkagltf.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.qwerty.geometry}
        material={materials.Silk_Duchess_Satin_FRONT_35292}
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/futbolka/futbolkagltf.gltf");
