/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/maikanew/maika1/maika1.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Maika1(props) {
  const { nodes, materials } = useGLTF("/maikanew/maika1/maika1.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.maika1.geometry}
        material={materials.FABRIC_1_FRONT_2707}
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/maikanew/maika1/maika1.gltf");
