/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/rukovanew/rukovabezmanjet/rukovabezmanjet.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Rukovabezmanjet(props) {
  const { nodes, materials } = useGLTF(
    "/rukovanew/rukovabezmanjet/rukovabezmanjet.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.rukovabezmanjet.geometry}
        material={materials["FABRIC_1_FRONT_2707.014"]}
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/rukovanew/rukovabezmanjet/rukovabezmanjet.gltf");
