/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/shtany/shtany.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shtany(props) {
  const { nodes, materials } = useGLTF("/shtany/shtany.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.shtany.geometry}
        material={materials.FABRIC_1_FRONT_2031}
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/shtany/shtany.gltf");
