/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/tolstovka/tolstovka.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Tolstovka(props) {
  const { nodes, materials } = useGLTF("/tolstovka/tolstovka.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tolstovka.geometry}
        material={materials["Knit_Fleece_Terry_FRONT_899062.001"]}
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/tolstovka/tolstovka.gltf");
