/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hoodie.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Hoodie(props) {
  const { nodes, materials } = useGLTF("./forcards/hoodie.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -11, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}>
        <mesh
          geometry={nodes.hoodie_1.geometry}
          material={materials.Rib_2X2_468gsm_hoodie_end}
        />
        <mesh
          geometry={nodes.hoodie_2.geometry}
          material={materials.Sweat_Rib_1X1_319gsm_hoodie}
        />
        <mesh
          geometry={nodes.hoodie_3.geometry}
          material={materials.Sweat_hood_Rib_1X1_319gsm_hood}
        />
        <mesh
          geometry={nodes.hoodie_4.geometry}
          material={materials.stitches}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/hoodie.glb");
