/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model2/scene.gltf -r public
Author: mezuna (https://sketchfab.com/mezuna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/female-anatomy-women-highpoly-add580d1877b4b6fa5e4ea90edfabc35
Title: Female anatomy | Women Highpoly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Button } from "@mui/material";

export function Body2(props) {
  const { nodes, materials } = useGLTF("/model2/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_1.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_2.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_3.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_4.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_5.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_6.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_7.geometry}
          material={materials.Merged_scetc1}
        />
        <mesh
          geometry={nodes.Merged_scetc1_Merged_scetc1_0_8.geometry}
          material={materials.Merged_scetc1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model2/scene.gltf");
