/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model4/untitled.gltf -r public
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Body4(props) {
  const { nodes, materials } = useGLTF("/model4/untitled.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.95, -10, -0.08]}
        rotation={[Math.PI / 2, 0, -1.62]}
        scale={0.01}
      >
        <mesh
          geometry={nodes["avatar-women_1"].geometry}
          material={materials.dummySG1SG1}
        />
        <mesh
          geometry={nodes["avatar-women_2"].geometry}
          material={materials.W_Shoes_skinSG1SG1SG1}
        />
        <mesh
          geometry={nodes["avatar-women_3"].geometry}
          material={materials.HEELSG1SG1}
        />
        <mesh
          geometry={nodes["avatar-women_4"].geometry}
          material={materials.hair2}
        />
        <mesh
          geometry={nodes["avatar-women_5"].geometry}
          material={materials["Mara:face2"]}
        />
        <mesh
          geometry={nodes["avatar-women_6"].geometry}
          material={materials["Mara:body3"]}
        />
        <mesh
          geometry={nodes["avatar-women_7"].geometry}
          material={materials["Mara:arm2"]}
        />
        <mesh
          geometry={nodes["avatar-women_8"].geometry}
          material={materials["Mara:leg2"]}
        />
        <mesh
          geometry={nodes["avatar-women_9"].geometry}
          material={materials["Mara:eye2"]}
        />
        <mesh
          geometry={nodes["avatar-women_10"].geometry}
          material={
            materials["Mara:skin_14:skin_13:skin_11:skin_10:pose:pose:eyelash1"]
          }
        />
        <mesh
          geometry={nodes["avatar-women_11"].geometry}
          material={materials["Mara:tooth2"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model4/untitled.gltf");
